"""empty message

Revision ID: 12845c56c99a
Revises: 478ca327ca1b
Create Date: 2024-03-11 20:13:10.203770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12845c56c99a'
down_revision = '478ca327ca1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
