"""empty message

Revision ID: 12b4b90899de
Revises: e96a4f3ce6a2
Create Date: 2024-09-28 17:43:23.278171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12b4b90899de'
down_revision = 'e96a4f3ce6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_items', sa.Column('podcast_id', sa.Integer(), nullable=True))
    op.add_column('podcast_items', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_podcast_items_podcast_id'), 'podcast_items', ['podcast_id'], unique=False)
    op.create_foreign_key(None, 'podcast_items', 'podcasts', ['podcast_id'], ['id'])
    op.add_column('podcasts', sa.Column('subtitle', sa.String(), nullable=True))
    op.alter_column('podcasts', 'author',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='author::json')
    op.alter_column('podcasts', 'category',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='category::json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podcasts', 'category',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('podcasts', 'author',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('podcasts', 'subtitle')
    op.drop_constraint(None, 'podcast_items', type_='foreignkey')
    op.drop_index(op.f('ix_podcast_items_podcast_id'), table_name='podcast_items')
    op.drop_column('podcast_items', 'type')
    op.drop_column('podcast_items', 'podcast_id')
    # ### end Alembic commands ###
