"""empty message

Revision ID: 217ab2f1ecee
Revises: 72f8796c8001
Create Date: 2024-03-18 16:25:20.416943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217ab2f1ecee'
down_revision = '72f8796c8001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('time_subscribed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_subscribed')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
