"""empty message

Revision ID: 22e33a3dcefd
Revises: 5ab50cda20f0
Create Date: 2024-01-01 16:00:01.872074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e33a3dcefd'
down_revision = '5ab50cda20f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleep_diaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('last_night_get_into_bed_time', sa.String(), nullable=True),
    sa.Column('last_night_turn_off_light_time', sa.String(), nullable=True),
    sa.Column('last_night_time_to_fall_asleep_in_minutes', sa.Integer(), nullable=True),
    sa.Column('last_night_number_of_times_wakeup', sa.Integer(), nullable=True),
    sa.Column('last_night_each_wakeup_time_in_minutes', sa.String(), nullable=True),
    sa.Column('this_morning_wakeup_time', sa.String(), nullable=True),
    sa.Column('this_morning_get_out_of_bed_time', sa.String(), nullable=True),
    sa.Column('last_night_sleep_quality', sa.String(), nullable=True),
    sa.Column('negative_sleep_thought', sa.String(), nullable=True),
    sa.Column('positive_sleep_thought', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_diaries_user_id'), 'sleep_diaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleep_diaries_user_id'), table_name='sleep_diaries')
    op.drop_table('sleep_diaries')
    # ### end Alembic commands ###
