"""empty message

Revision ID: 23575c78b37d
Revises: 32087fc61659
Create Date: 2023-11-19 17:00:00.304909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23575c78b37d'
down_revision = '32087fc61659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    message_type = postgresql.ENUM('USER', 'BOT', name='message_type')
    message_type.create(op.get_bind())
    op.add_column('messages', sa.Column('type', sa.Enum('USER', 'BOT', name='message_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tyep')
    message_type = postgresql.ENUM('USER', 'BOT', name='message_type')
    message_type.drop(op.get_bind())
    # ### end Alembic commands ###
