"""empty message

Revision ID: 32087fc61659
Revises: de345fc9e072
Create Date: 2023-11-19 16:33:03.853219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32087fc61659'
down_revision = 'de345fc9e072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('guest', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_guest'), 'messages', ['guest'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_guest'), table_name='messages')
    op.drop_column('messages', 'guest')
    # ### end Alembic commands ###
