"""empty message

Revision ID: 478ca327ca1b
Revises: 68b96a8952ef
Create Date: 2024-02-27 20:03:05.971271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478ca327ca1b'
down_revision = '68b96a8952ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_diaries', 'last_night_get_into_bed_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using = "last_night_get_into_bed_time::integer")
    op.alter_column('sleep_diaries', 'last_night_turn_off_light_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using = "last_night_turn_off_light_time::integer")
    op.alter_column('sleep_diaries', 'this_morning_wakeup_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using = "this_morning_wakeup_time::integer")
    op.alter_column('sleep_diaries', 'this_morning_get_out_of_bed_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using = "this_morning_get_out_of_bed_time::integer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_diaries', 'this_morning_get_out_of_bed_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('sleep_diaries', 'this_morning_wakeup_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('sleep_diaries', 'last_night_turn_off_light_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('sleep_diaries', 'last_night_get_into_bed_time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
