"""empty message

Revision ID: 5ab50cda20f0
Revises: b42e2b41051b
Create Date: 2023-12-28 16:00:41.910064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab50cda20f0'
down_revision = 'b42e2b41051b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'thread_id')
    # ### end Alembic commands ###
