"""empty message

Revision ID: 5f3bda0117cd
Revises: 4e440be7c499
Create Date: 2023-12-01 21:29:02.216455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f3bda0117cd'
down_revision = '4e440be7c499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'attributes')
    # ### end Alembic commands ###
