"""empty message

Revision ID: 611e7c12ed35
Revises: 23575c78b37d
Create Date: 2023-11-21 16:11:19.101129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '611e7c12ed35'
down_revision = '23575c78b37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('messages', 'type',
    #            existing_type=postgresql.ENUM('USER', 'BOT', name='message_type'),
    #            type_=sa.Enum('USER', 'BOT', name='messagetype'),
    #            existing_nullable=True)
    op.add_column('users', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'data')
    # op.alter_column('messages', 'type',
    #            existing_type=sa.Enum('USER', 'BOT', name='messagetype'),
    #            type_=postgresql.ENUM('USER', 'BOT', name='message_type'),
    #            existing_nullable=True)
    # ### end Alembic commands ###
