"""empty message

Revision ID: 68b96a8952ef
Revises: 9163878efcdf
Create Date: 2024-02-26 21:25:32.943139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b96a8952ef'
down_revision = '9163878efcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_diaries', 'last_night_sleep_quality',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using = "last_night_sleep_quality::integer"
               )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_diaries', 'last_night_sleep_quality',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
