"""empty message

Revision ID: 72f8796c8001
Revises: 12845c56c99a
Create Date: 2024-03-17 20:32:59.244689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f8796c8001'
down_revision = '12845c56c99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('time_subscribed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_subscribed')
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
