"""empty message

Revision ID: 9163878efcdf
Revises: 78eff07094ae
Create Date: 2024-02-19 13:45:56.504173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9163878efcdf'
down_revision = '78eff07094ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_diaries', 'last_night_each_wakeup_time_in_minutes',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='last_night_each_wakeup_time_in_minutes::json')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_diaries', 'last_night_each_wakeup_time_in_minutes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
