"""empty message

Revision ID: b068c1a5abbb
Revises: 217ab2f1ecee
Create Date: 2024-03-20 20:48:00.479460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b068c1a5abbb'
down_revision = '217ab2f1ecee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('customer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'customer')
    # ### end Alembic commands ###
