"""empty message

Revision ID: b42e2b41051b
Revises: 2f4c0103efe6
Create Date: 2023-12-16 18:19:50.905906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42e2b41051b'
down_revision = '2f4c0103efe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('thread_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'thread_id')
    # ### end Alembic commands ###
