"""empty message

Revision ID: e96a4f3ce6a2
Revises: 4c1c0508200b
Create Date: 2024-09-27 16:58:32.105149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96a4f3ce6a2'
down_revision = '4c1c0508200b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('explicit', sa.String(), nullable=True),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_guid'), 'podcasts', ['guid'], unique=False)
    op.create_index(op.f('ix_podcasts_user_id'), 'podcasts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcasts_user_id'), table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_guid'), table_name='podcasts')
    op.drop_table('podcasts')
    # ### end Alembic commands ###
